// Package exchange converts hosts to and from portable file formats.
package exchange

import (
	"context"
	"errors"
	"fmt"
	"io"
	"regexp"
	"strings"

	"github.com/BurntSushi/toml"

	"github.com/ProductionPanic/rootnet-cli/internal/store"
)

type tomlFile struct {
	Hosts []store.Host `toml:"host"`
}

// WriteTOML writes hosts as a TOML document with one [[host]] table each.
func WriteTOML(w io.Writer, hosts []store.Host) error {
	out := make([]store.Host, len(hosts))
	for i, h := range hosts {
		if h.Port == 22 {
			h.Port = 0 // omit the default
		}
		out[i] = h
	}
	return toml.NewEncoder(w).Encode(tomlFile{Hosts: out})
}

// ReadTOML parses a document written by WriteTOML.
func ReadTOML(r io.Reader) ([]store.Host, error) {
	var f tomlFile
	md, err := toml.NewDecoder(r).Decode(&f)
	if err != nil {
		return nil, err
	}
	if und := md.Undecoded(); len(und) > 0 {
		return nil, fmt.Errorf("unknown keys: %v", und)
	}
	return f.Hosts, nil
}

var unsafeAlias = regexp.MustCompile(`[^A-Za-z0-9._-]+`)

// SSHConfigAlias turns a host name into something usable as an ssh_config
// Host pattern.
func SSHConfigAlias(name string) string {
	return strings.Trim(unsafeAlias.ReplaceAllString(name, "-"), "-")
}

// WriteSSHConfig writes hosts as ssh_config(5) entries.
func WriteSSHConfig(w io.Writer, hosts []store.Host) error {
	if _, err := fmt.Fprintln(w, "# Generated by rootnet. Edits will be overwritten on the next export."); err != nil {
		return err
	}
	for _, h := range hosts {
		alias := SSHConfigAlias(h.Name)
		if alias == "" {
			continue
		}
		var b strings.Builder
		fmt.Fprintf(&b, "\nHost %s\n", alias)
		fmt.Fprintf(&b, "    HostName %s\n", h.Hostname)
		if h.User != "" {
			fmt.Fprintf(&b, "    User %s\n", h.User)
		}
		if h.Port != 0 && h.Port != 22 {
			fmt.Fprintf(&b, "    Port %d\n", h.Port)
		}
		if h.IdentityFile != "" {
			fmt.Fprintf(&b, "    IdentityFile %s\n", h.IdentityFile)
		}
		if h.JumpHost != "" {
			fmt.Fprintf(&b, "    ProxyJump %s\n", h.JumpHost)
		}
		if _, err := io.WriteString(w, b.String()); err != nil {
			return err
		}
	}
	return nil
}

// Result summarises an import.
type Result struct {
	Created, Updated int
	Errors           []error
}

// Import upserts hosts by name. When overwrite is false, existing hosts are
// left untouched and counted as errors.
func Import(ctx context.Context, s *store.Store, hosts []store.Host, overwrite bool) Result {
	var res Result
	for _, h := range hosts {
		existing, err := s.Get(ctx, h.Name)
		switch {
		case errors.Is(err, store.ErrNotFound):
			if _, err := s.Create(ctx, h); err != nil {
				res.Errors = append(res.Errors, fmt.Errorf("%s: %w", h.Name, err))
				continue
			}
			res.Created++
		case err != nil:
			res.Errors = append(res.Errors, fmt.Errorf("%s: %w", h.Name, err))
		case !overwrite:
			res.Errors = append(res.Errors, fmt.Errorf("%s: already exists (use --overwrite)", h.Name))
		default:
			h.ID = existing.ID
			if _, err := s.Update(ctx, h); err != nil {
				res.Errors = append(res.Errors, fmt.Errorf("%s: %w", h.Name, err))
				continue
			}
			res.Updated++
		}
	}
	return res
}
